### ISSUE TITLE
error `attempt to subtract with overflow` when trying to build spandex/examples/text

### ISSUE THREAD

**Issue by astrale-sharp** [rust-spandex/spandex#18]
Hey there, what a great idea your crate!

I can't build one of the project example though :3
```
❯ pwd
/home/astrale/playground/spandex/examples/text
❯ cargo run -- build
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `/home/astrale/playground/spandex/target/debug/spandex build`
thread 'main' panicked at 'attempt to subtract with overflow', src/layout/paragraphs/engine.rs:221:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
❯cargo run --release -- build
    Finished release [optimized] target(s) in 0.07s
     Running `/home/astrale/playground/spandex/target/release/spandex build`
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', src/layout/paragraphs/engine.rs:224:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Note that the error in release is `'index out of bounds: the len is 0 but the index is 0'` contrary to what the title of this issue implied

Much love,
Astrale

**Comment by tforgione** [comment]
Good catch. This example was one that I made at the very beginning of this project. Then we focused on the markdown-like syntax and kinda ditched the text example. Not sure where the bug comes from, but renaming the file to "main.dex" fixes the issue. Not sure why, but it's now fixed. Thanks for the issue !
